name: Pull Request CI

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: 액션/체크아웃@v3
        uses: actions/checkout@v3

      - name: 의존성 설치
        run: yarn install

      - name: 테스트
        run: yarn test
